### ISSUE TITLE
Kindly Read!

### ISSUE THREAD

**Issue by rajinderpalsingh2001** [makesmatheasy/makesmatheasy-documentation#114]
## Certificate of OpenSource Contribution

All GSSOC'21 Participants who Contributed to Makes Math Easy **Documentation** Repository, with atleast 1 PR merged.

Kindly fill the form, sent in the GSSOC makesmatheasy Discord Channel **before 10 June,2021**

**Comment by rajinderpalsingh2001** [comment]
Participants who Contributed to Makes Math Easy Documentation Project Repository with atleast 1 PR merged

Kindly Fill this form to receive Certificate of Contribution

https://forms.gle/jxpYkgu614swdajc6

**Comment by rajinderpalsingh2001** [comment]
@madihamallick
@Inventor77
@anirudhsai20
@rukundob451
@KajalSinghBAGHEL
@Rishikakanojia
@RuchiGitHu
@SamikshaSankar
@sandra9711
@tarunsinghofficial
@simran1199

just a gentle Reminder

**Comment by rukundob451** [comment]
Thank you so much for this really grateful for what I was able to learn and still learning more continuously
