### ISSUE TITLE
updating vector section and fourier section under calculus

### ISSUE THREAD

**Issue by robinsingh-ai** [makesmatheasy/makesmatheasy-documentation#118]
hey @sairish2001 I would like to work on this issue as a GSSOC21 participant and will provide all the info related to calculus section on vector section and fourier section under calculus along with all the necessary formulas and info

Kindly assign me this issue, I shall be very thankful to you

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 31May,2021
