### ISSUE TITLE
adding beta gamma docs along with maxima,minima and power series under calculus

### ISSUE THREAD

**Issue by robinsingh-ai** [makesmatheasy/makesmatheasy-documentation#119]
hey @sairish2001 I would like to work on this issue as a GSSOC21 participant and will provide all the info related to calculus section on adding beta gamma docs along with maxima,minima and power series under calculus under calculus along with all the necessary formulas and info

Kindly assign me this issue, I shall be very thankful to you

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 31May,2021
