### ISSUE TITLE
Enhacing the Home Page UI

### ISSUE THREAD

**Issue by Inventor77** [makesmatheasy/makesmatheasy-documentation#12]
## **Problems I would like to Highlight**

- Burger Menu on Right Corner Gives bit bad impression on UI
- No Animation at all on burger Menu
- No top Navbar 
- Home and  About menu with our main Feature of Websites 

## **The solution you'd like**

- First I would like to add a top NavBar to our website 
- Moving the Home and About to Top Navbar 
- Improving the UI of Burger Menu 
- Adding a subtle Animation to Burger Menu 
- Adding Icons top Each Maths Sections 

**Additional context**
Mentors, it is a considerable amount of change in the concept of overall website, so the thing I ask is to let me make the necessary changes in my own remote version to which I will showcase the website after bringing some changes and if it is considerable enough to be implemented, 
Can Mentors overlook on this and feels if it is worth changing Please assign me this issue and labeling it with **Gssoc21**

https://user-images.githubusercontent.com/62959484/113183963-45ce3100-9272-11eb-9a8b-f1b28d8159c5.mp4

**Comment by Inventor77** [comment]
@robin025 @sairish2001 Mentors , I'm Maths Enthusiast and would love to contribute to this please Project. Please Let me Assign this Issue

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST
