### ISSUE TITLE
Adding Search Bar 

### ISSUE THREAD

**Issue by Inventor77** [makesmatheasy/makesmatheasy-documentation#13]
## **New Feature**

- Adding Search Bar (Only UI) help visitor to navigate to his own desired Topic

## **The solution**

- Search Bar with search Icon on It with Subtle Animation on Focus or while search bar is activated

**Comment by Inventor77** [comment]
@robin025  @sairish2001  Can Mentors overlook on this and feels worth changing Please assign me this issue and labeling it with gssoc21

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 5 April,2021 11:59 PM IST

**Comment by rajinderpalsingh2001** [comment]
any update?

**Comment by Inventor77** [comment]
sir I'm the one who is unable to setup the project . As soon as I'm able to run Rails server on my Machine I will PR for both the Issue within some hour

**Comment by Inventor77** [comment]
@sairish2001 Please sir help me with it
