### ISSUE TITLE
Fixing a small typo in config.yml and adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by robinsingh-ai** [makesmatheasy/makesmatheasy-documentation#14]
hey @sairish2001 Actually earlier the name of this repo was **Makes-Math-Easy-Documentation**, so i have added the Base URL same as the previous Repo Name as **Makes-Math-Easy-Documentation**, but as you changed the repo name, now GitHub is adding **makesmatheasy-documentation** in the URL which is not same as the current Base URL for this website

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 7 April,2021 11:59 PM IST

**Comment by robinsingh-ai** [comment]
@sairish2001 already done it and created a PR, but I think don't merge it now because many new contributors are asking for "how to setup the environment " so right now i am creating a markdown file which will specify how ho setup this project 
so after that i will squash and rebase all the commits, then you can review , if that's sounds good to you
