### ISSUE TITLE
Enhance navbar

### ISSUE THREAD

**Issue by Rishikakanojia** [makesmatheasy/makesmatheasy-documentation#18]
Hey @sairish2001  ,Home button in navbar isn't working properly. Can I fix it?
If you find this issue meaningful then please assign it to me .
Thank you.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST

**Comment by Rishikakanojia** [comment]
Thank You Sir.
