### ISSUE TITLE
Responsivness of website 

### ISSUE THREAD

**Issue by shefali12-ab** [makesmatheasy/makesmatheasy-documentation#192]
I will like to work on the frontend part of the project, by making the website responsive.

**Comment by rajinderpalsingh2001** [comment]
@shefali12-ab You are refering to documentation or the main website?

**Comment by shefali12-ab** [comment]
I am referring to the main website.

**Comment by rajinderpalsingh2001** [comment]
Thanks for showing interest, please create issue in the [main repo.](https://github.com/makesmatheasy/makesmatheasy) and then I will assign you

**Comment by shefali12-ab** [comment]
> Thanks for showing interest, please create issue in the [main repo.](https://github.com/makesmatheasy/makesmatheasy) and then I will assign you

Sir, I have seen the website of the main repo [https://makesmatheasy.github.io/makesmatheasy/](url)
 it is already responsive . like the home, favorite, calculator section bar is taking the footer section on changing the size of viewport. You can suggest me changes.

**Comment by rajinderpalsingh2001** [comment]
![Screenshot_20210912-194442_Chrome.jpg](https://user-images.githubusercontent.com/60106112/132991027-82a180c3-be66-4034-8c7d-ab7bbadeafaa.jpg)

Check this, you can try to fix this

if needs any help in locating the files or anything do ask!

There's unexpected spaces all over, in the bottom from the Bottom navbar, and also at the right,left

**Comment by shefali12-ab** [comment]
> ![Screenshot_20210912-194442_Chrome.jpg](https://user-images.githubusercontent.com/60106112/132991027-82a180c3-be66-4034-8c7d-ab7bbadeafaa.jpg)
> 
> Check this, you can try to fix this
> 
> if needs any help in locating the files or anything do ask!
> 
> There's unexpected spaces all over, in the bottom from the Bottom navbar, and also at the right,left

okay, also one suggestion I think it looks good if instead of appearing at the bottom this part will appear above like a navigation bar.
