### ISSUE TITLE
Image in About Section Overflowing

### ISSUE THREAD

**Issue by Castella1313** [makesmatheasy/makesmatheasy-documentation#23]
Image in About Section Overflowing

![Screenshot 2021-04-08 at 8 16 30 PM](https://user-images.githubusercontent.com/53293156/114047609-6f590f00-98a7-11eb-9cff-e3e4b07a2b71.png)

**Comment by Castella1313** [comment]
@sairish2001 May I work on it?

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by Castella1313** [comment]
I can't find this issue now!! I don't know who fixed it
