### ISSUE TITLE
 Navbar Bug

### ISSUE THREAD

**Issue by Inventor77** [makesmatheasy/makesmatheasy-documentation#24]
##  ****``Bug``****

- Image is moving above navbar
- Seems opacity of navbar is less makes it see some words through it 

![Screenshot (595)](https://user-images.githubusercontent.com/62959484/114073733-3d54a680-98c1-11eb-8fb1-e3fed7e9f90e.png)

**Comment by Inventor77** [comment]
@sairish2001 Please sir let me solve this mistake by me

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 11 April,2021 11:59 PM IST
