### ISSUE TITLE
Can i add favicon to this website ?I am a participant in gssoc.

### ISSUE THREAD

**Issue by Ayushgup85** [makesmatheasy/makesmatheasy-documentation#25]

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by Bhavya-Sehgal** [comment]
If no one is working , can I work on this issue ?
Please assign me this issue @sairish2001

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 please assign me this issue

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 25 April,2021

Favicon is already there in the MakesMathEasy main repo. you can just pick it from there
