### ISSUE TITLE
Adding functionality to h1 tag

### ISSUE THREAD

**Issue by tarunsinghofficial** [makesmatheasy/makesmatheasy-documentation#27]
I think we can add a home page link to the logo and h1 tag in the navbar!

can I fix it?

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 I want to work on this issue. Please assign me this issue
