### ISSUE TITLE
In Nav bar, home button and search bar are overlapping.

### ISSUE THREAD

**Issue by surbhi594** [makesmatheasy/makesmatheasy-documentation#30]
Please assign this issue to me as I'm a participant of GSSOC'21.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 17 April,2021 11:59 PM IST

**Comment by Bhavya-Sehgal** [comment]
I want to fix this navbar issue 
Please assign me this issue @sairish2001

**Comment by surbhi594** [comment]
This issue is already been resolved.
