### ISSUE TITLE
Icons for closing and opening of sidenav are wrong.

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy-documentation#33]
![side1](https://user-images.githubusercontent.com/57946528/114437317-01cd1b80-9be4-11eb-9694-a4db48932d90.png)
![side2](https://user-images.githubusercontent.com/57946528/114437325-04c80c00-9be4-11eb-9d8d-faf6c4694a87.png)

'X' should be shown when sidenav is open, but it is shown after the sidenav had been closed.

Please assign me this issue, I would like to work on this.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST
