### ISSUE TITLE
Update conversion tools content

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy-documentation#34]
I would like to update it as more of unit converter have been added to makesmatheasy site. Please assign me this issue as a gssoc participant.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 18 April,2021 11:59 PM IST

**Comment by shonali2600** [comment]
@sairish2001 can you please help me in running this on my local.
Following is the screenshot of what happens when I click Go live on default.html
![mathdoc](https://user-images.githubusercontent.com/57946528/114596671-88016480-9cad-11eb-8e30-5c8e31ce251b.png)
