### ISSUE TITLE
Make Website responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [makesmatheasy/makesmatheasy-documentation#35]
I want to make all the pages of website responsive in various screen sizes.

[GSSOC'21]

Please assign me this issue.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST

**Comment by Bhavya-Sehgal** [comment]
Do I have to make navbar responsive too as it was already assigned to someone in another issue .
Please confirm @sairish2001
