### ISSUE TITLE
Adding some new features

### ISSUE THREAD

**Issue by wajeehamushtaq** [makesmatheasy/makesmatheasy-documentation#37]
The following features I want to add to the site.
-> Add makesmatheasy logo on the top left corner of the site
-> Add tooltip on the simple calculator.
-> Adding gradient colors on hover including pink color.

**Comment by wajeehamushtaq** [comment]
I am a gssoc'21 participant please assign this issue to me.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 19 April,2021 11:59 PM IST

**Comment by subhangi2731** [comment]
can you assign me I will make a pr by tomorrow
