### ISSUE TITLE
Adding Binary Calculations part

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy-documentation#50]
![bb](https://user-images.githubusercontent.com/70858557/115139787-8fc85c80-a051-11eb-8e6a-c0de24680c8d.PNG)

Here I would like to add the Binary calculation part also. Please assign this to me.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 25 April,2021 11:59 PM IST
