### ISSUE TITLE
Repeated and Useless content in the first page

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy-documentation#64]
There are some headings that are repeated thrice, and some useless content showing at the end, and some content is not clearly visible in light mode.
![mathdoc-content2](https://user-images.githubusercontent.com/57946528/115819909-6f1b5080-a41d-11eb-9551-d8a5505e0d41.png)

![mathdoc-content](https://user-images.githubusercontent.com/57946528/115820069-bbff2700-a41d-11eb-88f2-7b3ea532a17c.png)

Kindly assign it to me.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 28 April,2021

**Comment by shonali2600** [comment]
not able to reach that page again
