### ISSUE TITLE
Side nav visited link looking different

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy-documentation#65]
Visited Link in side-nav has a different color which is not needed here, also not looking good. Additionally in dark mode, the unvisited link does not appear clearly.
I would like to rectify all these problems additionally I would like to change the color of the `active` link here.

Kindly assign it to me.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 28 April,2021
