### ISSUE TITLE
tables in all the sections has no border visible

### ISSUE THREAD

**Issue by robinsingh-ai** [makesmatheasy/makesmatheasy-documentation#68]
![Screenshot (417)](https://user-images.githubusercontent.com/55009875/115876465-f8ee0c80-a463-11eb-9378-7c990e666d83.png)
hey @sairish2001  tables in all the docs have no border color and border thickness, which is causing confusion between columns and rows
Assign me this issue

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 28 April,2021
