### ISSUE TITLE
README is very short - Elaborate the README

### ISSUE THREAD

**Issue by riya3000** [makesmatheasy/makesmatheasy-documentation#7]
Hello Team, I was going through the README of this project. I feel the need to elaborate on the README. I want to describe this project in more detail, so everyone can understand the project better. I have started working on describing the project in more detail.
Please assign me to here. I am a gssoc'21 participant. Thank you @robin025 @sairish2001

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 31 March,2021 (11:59 PM IST)

**Comment by Rishikakanojia** [comment]
Can I work on this issue?

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 12 April,2021 11:59 PM IST

**Comment by anirudhsai20** [comment]
Hi @sairish2001. Can you please answer few of my questions? 
1. Have you used any other Tech stack or programming language other than - HTML, Ruby, JavaScript ans CSS?
2. Can you please describe what exactly is Makesmatheasy so that I can provide a clear and in-depth description of the same?

**Comment by rajinderpalsingh2001** [comment]
Ruby is used in documentation only

The tech stack of main project is HTML,CSS, JAVASCRIPT

And the aim of this project is to provide, stepwise solutions to Various math problems. 
With no server side interaction, only client side processing hence provides speed.

I think this is enough for you to get an rough idea about Project

**Comment by nityaak5** [comment]
Hi! I would like to work on this issue. Is it still available?
