### ISSUE TITLE
Dark mode icon not visible in sidebar

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [makesmatheasy/makesmatheasy-documentation#71]
I want to align the dark mode icon on the sidebar. Also I want to align home and about in accordance to the other sections links.

[GSSOC'21]

Please assign me this issue @sairish2001 

Screenshot:

![icondark](https://user-images.githubusercontent.com/66208607/115912195-a1b06200-a48c-11eb-90b9-824a39bf1846.png)

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 28 April,2021
