### ISSUE TITLE
Bed hover color in website name.

### ISSUE THREAD

**Issue by RuchiGitHu** [makesmatheasy/makesmatheasy-documentation#80]
When we use hover effect which means that we want to highlight thing whenever we point there. But in the name of website, after pointing it the hover color makes it difficult to read it. Home and About is more readable when we hover it like that the name of website should also more readable after hovering it.
I want to change hover color there.
Before Hovering it.
![image](https://user-images.githubusercontent.com/71754179/116000968-f5978400-a60f-11eb-9948-87a5f887e115.png)

After hover.
![image](https://user-images.githubusercontent.com/71754179/116000983-01834600-a610-11eb-86be-4c8d437b6808.png)

Please assign this issue to me....
also let me know if you can see images in this PR as it not showing to me...

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 1 May, 2021

Yes images are visible
