### ISSUE TITLE
Adding tools in the Trigonometry section 

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy-documentation#89]
I would like to work on this issue. Please assign this to me.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 11 May,2021

**Comment by GuptaTanisha** [comment]
Can I work on this issue?

**Comment by madihamallick** [comment]
@GuptaTanisha I'm working on this. I'll make a PR soon.
