### ISSUE TITLE
Adding badges to readme.

### ISSUE THREAD

**Issue by simran1199** [makesmatheasy/makesmatheasy-documentation#90]
I would like to add badges(like contributors, forks, stars, issues etc.) in the readme. Please assign me this issue.

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 10 May,2021

**Comment by simran1199** [comment]
I have updated the readme file with all the necessary badges. Please have a look.

**Comment by simran1199** [comment]
I have updated the readme file with all the necessary badges. Please have a look as I have created the pull request.
