### ISSUE TITLE
Bug in Complex numbers documentation

### ISSUE THREAD

**Issue by tanvi355** [makesmatheasy/makesmatheasy-documentation#95]
There is a spelling mistake in the heading. Also, the identities' powers are not properly stated and the layout of a paragraph is out of line.
![image](https://user-images.githubusercontent.com/56465105/117093031-6b70bd80-ad7d-11eb-8d3a-289cfb487e20.png)
![image](https://user-images.githubusercontent.com/56465105/117093067-82afab00-ad7d-11eb-9fca-4d05605ae146.png)

I will also correct any other mistakes if present.

**Comment by tanvi355** [comment]
Please assign this to me under GSSoC'21 @sairish2001

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 10 May,2021
