### ISSUE TITLE
Bug in conic section

### ISSUE THREAD

**Issue by tanvi355** [makesmatheasy/makesmatheasy-documentation#98]
Graphs are not visible in any of the tables.
![image](https://user-images.githubusercontent.com/56465105/117489542-5e291e00-af8b-11eb-9c63-6f4c59aed31d.png)

I would like to fix this and make some minor changes if needed.

**Comment by tanvi355** [comment]
@sairish2001 please assign this to me

**Comment by rajinderpalsingh2001** [comment]
Go ahead
Deadline 15 May,2021
